# Generated by Django 4.1.7 on 2023-03-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Injection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("ui", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "type",
                    models.CharField(
                        choices=[("F", "Fast acting"), ("L", "Long acting")],
                        max_length=1,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injections",
                        to="person.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
