# Generated by Django 4.1.7 on 2023-03-11 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import person.model_validator


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.TextField(
                        validators=[person.model_validator.validate_length]
                    ),
                ),
                (
                    "last_name",
                    models.TextField(
                        validators=[person.model_validator.validate_length]
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("fast_acting_insulin", models.TextField()),
                ("long_acting_insulin", models.TextField()),
                ("is_carb_counting", models.BooleanField(default=False)),
                (
                    "breakfast_count",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "lunch_count",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "snack_count",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "dinner_count",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "breakfast_dosage",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "lunch_dosage",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "snack_dosage",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "dinner_dosage",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                ("correction_factor", models.PositiveSmallIntegerField(default=35)),
                ("min_glycemia", models.PositiveSmallIntegerField(default=80)),
                ("max_glycemia", models.PositiveSmallIntegerField(default=95)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
