# Generated by Django 4.1.7 on 2023-03-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="diabetes_type",
            field=models.CharField(
                choices=[
                    ("P", "Pre diabetes"),
                    ("1", "Diabetes type 1"),
                    ("2", "Diabetes type 2"),
                ],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
