# Generated by Django 4.1.7 on 2023-03-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("injection", "0001_initial"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "cho",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Grams of carbohydrate",
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Grams of protein"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("B", "Breakfast"),
                            ("L", "Lunch"),
                            ("S", "Snack"),
                            ("D", "Dinner"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "injection",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="injection.injection",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="person.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
